feat: docker compose prod

diff --git a/Server/dockerfile b/Server/dockerfile
--- a/Server/dockerfile
+++ b/Server/dockerfile
@@ -1,25 +1,45 @@
-ARG NODE_VERSION=24.11.1-alpine
-
-FROM node:${NODE_VERSION} AS base
-# Set working directory
+FROM --platform=linux/amd64 node:20-alpine AS deps
+RUN apk add --no-cache libc6-compat openssl
 WORKDIR /app
 
-# Create non-root user for security
-RUN addgroup -g 1001 -S nodejs && \
-    adduser -S nodejs -u 1001 -G nodejs && \
-    chown -R nodejs:nodejs /app
+# Install Prisma Client - remove if not using Prisma
 
-COPY package*.json ./
+COPY prisma ./
 
-RUN npm ci 
+# Install dependencies based on the preferred package manager
 
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./
+
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm i; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+##### BUILDER
+
+FROM --platform=linux/amd64 node:20-alpine AS builder
+ARG DATABASE_URL
+ARG NEXT_PUBLIC_CLIENTVAR
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-ARG DATABASE_URL
-RUN SKIP_ENV_VALIDATION=1 npm run build
+RUN \
+    if [ -f yarn.lock ]; then SKIP_ENV_VALIDATION=1 yarn build; \
+    elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm run build; \
+    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && SKIP_ENV_VALIDATION=1 pnpm run build; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+##### RUNNER
+FROM --platform=linux/amd64 gcr.io/distroless/nodejs20-debian12 AS runner
+WORKDIR /app
 
-USER nodejs
+ENV NODE_ENV production
+COPY --from=builder /app/dist ./dist
 
 EXPOSE 42069
+
 
 CMD [ "npm", "run", "start" ]
